version: "3"
services:
  selenium-tests:
    build: .
    depends_on:
      - chrome
    environment:
      - DISPLAY=:99
    volumes:
      - ./test-output:/app/test-output
    networks:
      - selenium-grid

  chrome:
    image: selenium/standalone-chrome:119.0
    shm_size: 2gb
    ports:
      - "4444:4444"
    networks:
      - selenium-grid

networks:
  selenium-grid:
    driver: bridge
